services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - tutorial-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - tutorial-redis:/var/lib/redis/data

  tutorial:
    build:
      context: .
    volumes:
      - ./tutorial:/opt/app
    links:
      - postgres
      - redis
    ports:
      - "8010:8010"
    env_file:
      - .env

  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq
    links:
      - postgres
      - redis
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    links:
      - tutorial
    ports:
      - "8020:8020"

volumes:
  tutorial-postgres:
  tutorial-redis:
